[package]
name = "pacman-json"
version = "0.1.1"
edition = "2021"

## https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpm = "2.2.2"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
